config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'tasks#index'

  resources :tasks

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord

validates :status, presence: true, length: { maximum: 10 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action :set_task,only:[:show, :edit, :update, :destroy]
	
  def index
    @task = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task =Task.new(task_params)

    if @task.save
       flash[:success]= 'Taskが正常に投稿されました'
       redirect_to @task
    else
       flash.now[:danger]= 'Taskが投稿されませんでした'
       render :new
    end
  end

  def edit
  end

  def update

    if @task.update(task_params)
      flash[:success] = 'Taskは正常に更新されました'
      redirect_to @task
    else
      flash.now[:danger]= 'Taskは更新されませんでした'
      render :edit
    end
  end

  def destroy
    @task.destroy

    flash[:success] = 'Taskは正常に削除されました'
    redirect_to tasks_url
    
  end

  private

  def set_task
    @task=Task.find(params[:id])
  end

  def task_params
     params.require(:task).permit(:content, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_flash_tasks.html.erb
<% flash.each do |task_tyape,task| %>

	<div>

<%= task %>

	</div>

<% end %>

app/views/layouts/_navbar.html.erb
<header>
<nav class="navbar navbar-inverse navbar-static-top">
<div class="container">
<div class="navbar-header">
<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-exp>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
<a class="navbar-brand" href="/">Kadai-Tasklist</a>
</div>
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
<ul class="nav navbar-nav navbar-right">
<li>
<%= link_to '新しいタスクの作成', new_task_path %>
</li>
</ul>
</div>
</div>
</nav>
</header>

app/views/layouts/_vavbar.html.erb
<header>
<nav class="navbar navbar-inverse navbar-static-top">
<div class="container">
<div class="navbar-header">
<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-exp
<span class="sr-only">Toggle navigation</span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
<a class="navbar-brand" href="/">Kadai-Tasklist</a>
</div>
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
<ul class="nav navbar-nav navbar-right">
<li>
<%= link_to '新しいタスクの作成', new_task_path %>
</li>
</ul>
</div>
</div>
</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>

    <meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Kadai-Tasklist</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  </head>

  <body>

  <%= render 'layouts/navbar' %>

	  <div class='container'>

<%= render 'layouts/flash_tasks' %>
<%= yield %>

	  </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<div class="row">

 <div class="col-xs-12 col-md-offset-2 col-md-8 col-lg-offset-3 col-lg-6">


<%= form_for(@task) do |f| %>

	<div class="form-group">

<%= f.label :status,'ステータス' %>

<%= f.text_field :status,class:'form-control' %>

	</div>

	<div class="form-group">

<%= f.label :content, 'タスク' %>

<%= f.text_field :content,class:'form-control' %>

	 </div>

<%= f.submit'作成',class:'btn btn-primary' %>

<% end %>

 </div>

</div>

app/views/tasks/edit.html.erb
<h1>id:

	<%= @task.id %>
	のタスク編集ページ</h1>

<%= render 'form',task:@task %>

<%= link_to '一覧に戻る',tasks_path %>

app/views/tasks/index.html.erb
<h1>現在のタスク一覧</h1>

<ul>

<% @task.each do |task| %>


	<li>
<%= link_to task.id,task %>
 :
<%= task.status %>
 &gt;
<%= task.content %>

        </li>

<% end %>

</ul>

<%= link_to'新しいタスクの作成', new_task_path %>

app/views/tasks/new.html.erb
<h1>新しいタスクの作成</h1>

<%= render'form',task:@task %>

<%=link_to '一覧に戻る',tasks_path %>

app/views/tasks/show.html.erb
<h1>id:

<%= @task.id %>
のタスク詳細ページ</h1>

<p>ステータス：
<%= @task.status %>
</p>


<p>タスク：
<%= @task.content %>
</p>

<%= link_to '一覧に戻る',tasks_path %>

<%= link_to 'タスクの編集',edit_task_path(@task) %>

<%= link_to 'このタスクを削除する', @task, method: :delete, data:{ confirm: '本当に削除してよろしいですか？'} %>